### ISSUE TITLE
Add an API for submitting comments.

### ISSUE THREAD

**Issue by RnbwNoise** [hnrysmth/reddit-api-client#13]
See http://www.reddit.com/dev/api#POST_api_comment. Updated comment.json:

	{
	  "operations": {
		"SubmitComment": {
		  "httpMethod": "POST",
		  "uri": "/api/comment",
		  "summary": "Submit a new comment",
		  "parameters": {
			"text": {
			  "location": "query",
			  "description": "The text to submit.",
			  "required": true,
			  "type": "string"
			},
			"thing_id": {
			  "location": "query",
			  "description": "Fullname of parent thing (a comment, or a link)",
			  "required": true,
			  "type": "string"
			}
		  }
		}
	  }
	}

**Comment by Zetaphor** [comment]
Created pull request #22

**Comment by Zetaphor** [comment]
Resolved in PR #22
